### ISSUE TITLE
Feature: Add Kaikoura to main NZ locatoins list

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis-api#39]
see https://en.wikipedia.org/wiki/Kaik%C5%8Dura

**done when:** 
 - [x] added to main list
 - [x] add option to process just some arbitrary (but valid location(s)) in analyser
 - [x] shows up in tests

**Comment by chrisbc** [comment]
new GT -> Solution flow raises 

```

2022-02-23T10:03:58.893+13:00Copy[ERROR] KeyError: 'Records'Traceback (most recent call last):  File "/var/task/api/process_solution.py", line 93, in handler    for evt in event['Records']: | [ERROR] KeyError: 'Records' Traceback (most recent call last):   File "/var/task/api/process_solution.py", line 93, in handler     for evt in event['Records']:
-- | --
```
